### ISSUE TITLE
omeka.omeka validation results

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#625]
### base omeka mapper issues
- [ ] identifier: suppress aws links -- look at current mapper logic for this -- see example in #26724 report

#26724 example with type: image/Image & identifier: AWS URLs
![Image](https://github.com/ucldc/rikolti/assets/32110172/36557eaf-ac8a-4799-936c-5e6a40a43ee7)

***
#### type enrichments
- [ ] type: we're expecting "image" but getting "Image" -- I believe we need/want the lowercase "image". Could you investigate where these should be transformed to lowercase "image"? (mapping, enrichment, etc?) -- see example in #26724 report
- [ ] type: some records have 2+ types indicated in the vernacular -- look at current mapper logic to see how it is normalizing -- see #27618 & #27625 reports

#27618 example of two types:
![Image](https://github.com/ucldc/rikolti/assets/32110172/96c84083-0462-4d80-bc84-dbd3a4804f34)

#27625 another example of two types:
![Image](https://github.com/ucldc/rikolti/assets/32110172/ceaa623b-ea1e-40cc-be42-a3f285e11cf4)

#### Verify whether these are addressed by the base oai mapper updates
- [ ] language: map language from `<dc:language>` -- Q: does omeka.omeka use the base oai mapper?
- [ ] source: map source from `<dc:source>` -- Q: does omeka.omeka use the base oai mapper?
- [ ] alternative title: map alternative title from `<dcterms:alternative>` -- Q: does omeka.omeka use the base oai mapper?
